version: "3"

services:
  mysql-service:
    image: mysql:latest
    container_name: mysql-standalone
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=blogapp
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=root
  springboot-service:

